/**
 * Stencil — the plugin's small CPU functions, ported to JavaScript.
 *
 *   Controls.cpp  what a 0..1 slider means (lengths in frame heights)
 *   Palette.cpp   Ink(): a layer's can, the darkest n of four
 *   Spray.cpp     the footprint's taps: exact areas of a disc in each texel
 *
 * The constants, the palettes and the option names are NOT typed here: they are
 * the generated block below, copied out of source/ by
 * demo/tools/sync_shaders.py and held to it by check_shaders.py. The functions
 * are hand translations, and only a reader checks them.
 *
 * **Float or double, as the C++ has it.** Controls.cpp works in `float`, so
 * each of its operations is rounded to single precision here with
 * `Math.fround`; `std::pow( 20.0f, v )` is Math.pow in double rounded once to
 * float, which can differ from a platform's powf in the last bit. Spray.cpp
 * works in double, as JavaScript does.
 */

//=== BEGIN GENERATED by demo/tools/sync_shaders.py (constants) from source/ -- do not edit by hand.
// source/Controls.h
export const CONTROLS_H = {
  kMinLayers: 1,
  kMaxLayers: 4,
  kSaturation: 0.9,
  kBridgeLift: 1.0,
  kSheetLift: 0.35,
  kPaletteCount: 5,
  kLayerColoursCount: 2,
  kWallCount: 4,
};
// source/Stencil.h
export const STENCIL_H = {
  kLatticeLines: 540,
  kKeepSlack: 1.0,
  kKeepRadius: 2,
};
// source/Shaders.h
export const SHADERS_H = {
  kNoSeed: 0xffffffff,
};
// source/Palette.h
export const PALETTE_H = {
  kCans: 4,
};
export const PLAIN_WALL = [0.93, 0.92, 0.89];
// source/Palette.cpp: five palettes of four cans, lightest first, straight RGB.
export const PALETTES = [
  [[0.72, 0.72, 0.71], [0.48, 0.48, 0.47], [0.24, 0.24, 0.24], [0.05, 0.05, 0.06]],
  [[0.86, 0.80, 0.64], [0.80, 0.13, 0.12], [0.20, 0.19, 0.20], [0.04, 0.04, 0.05]],
  [[0.78, 0.64, 0.45], [0.56, 0.40, 0.25], [0.33, 0.21, 0.12], [0.12, 0.07, 0.04]],
  [[0.98, 0.82, 0.10], [0.90, 0.20, 0.52], [0.13, 0.30, 0.78], [0.04, 0.04, 0.06]],
  [[0.66, 0.82, 0.86], [0.20, 0.56, 0.62], [0.12, 0.20, 0.40], [0.04, 0.05, 0.10]],
];
// The option lists: Controls.cpp PaletteName, LayerColoursName, WallName.
export const PALETTE_NAMES = ['Mono', 'Street', 'Sepia', 'Pop', 'Cool'];
export const LAYER_COLOURS_NAMES = ['Palette', 'From Clip'];
export const WALL_NAMES = ['Clip', 'Brick', 'Concrete', 'Plain'];
//=== END GENERATED (constants)

const f = Math.fround;
const clamp01 = (v) => f(Math.min(Math.max(v, 0), 1));
const clampInt = (v, lo, hi) => Math.min(Math.max(v, lo), hi);
/// std::lround for the values these see (never negative).
const lround = (v) => Math.round(v);

export const kPalette = { kMono: 0, kStreet: 1, kSepia: 2, kPop: 3, kCool: 4 };
export const kLayerColours = { kFromPalette: 0, kFromClip: 1 };
export const kWall = { kWallClip: 0, kWallBrick: 1, kWallConcrete: 2, kWallPlain: 3 };

//--------------------------------------------------------------- Controls.cpp

export function LayerCount(value) {
  return clampInt(lround(value), CONTROLS_H.kMinLayers, CONTROLS_H.kMaxLayers);
}

export function LayerThreshold(threshold, layer, layers) {
  layers = clampInt(layers, CONTROLS_H.kMinLayers, CONTROLS_H.kMaxLayers);
  layer = clampInt(layer, 1, layers);
  return f(f(clamp01(threshold) * (layers - layer + 1)) / layers);
}

export function SmoothSigmaHeights(value) {
  return f(f(0.01) * clamp01(value));
}

export function BridgeWidthHeights(value) {
  return f(f(0.001) * f(Math.pow(20, clamp01(value))));
}

export function BridgeWidthParam(heights) {
  return clamp01(f(f(Math.log(f(Math.max(heights, f(0.001)) / f(0.001)))) / f(Math.log(20))));
}

export function MinIslandSideHeights(value) {
  return f(f(0.05) * clamp01(value));
}

export function MinIslandParam(heights) {
  return clamp01(f(f(heights) / f(0.05)));
}

export function FootprintRadiusHeights(value) {
  return f(f(0.02) * clamp01(value));
}

export function DistanceParam(heights) {
  return clamp01(f(f(heights) / f(0.02)));
}

export function PressureAmount(value) {
  return f(2 * clamp01(value));
}

export function LiftSigmaHeights(value) {
  return f(f(0.008) * clamp01(value));
}

export function LiftAmount(value) {
  return clamp01(value);
}

export function DripChance(value) {
  return f(f(0.45) * clamp01(value));
}

export function DripLengthHeights(value) {
  return f(f(0.12) * clamp01(value));
}

export function OptionIndex(value, count) {
  return clampInt(lround(value), 0, count - 1);
}

//---------------------------------------------------------------- Palette.cpp

/// Layer `layer` (1 = the lightest, sprayed first) of `layers`: the darkest
/// `layers` cans, lightest first.
export function Ink(palette, layer, layers) {
  layers = clampInt(layers, CONTROLS_H.kMinLayers, CONTROLS_H.kMaxLayers);
  layer = clampInt(layer, 1, layers);
  const cans = PALETTES[clampInt(palette, 0, CONTROLS_H.kPaletteCount - 1)];
  return cans[PALETTE_H.kCans - layers + layer - 1];
}

//------------------------------------------------------------------ Spray.cpp

/// The antiderivative of sqrt( R^2 - x^2 ), for |x| <= R.
function chordIntegral(radius, x) {
  x = Math.min(Math.max(x, -radius), radius);
  const s = Math.sqrt(Math.max(0, radius * radius - x * x));
  return 0.5 * (x * s + radius * radius * Math.asin(x / radius));
}

/// Area of the disc inside { x <= a, y <= b }, in closed form.
function quadrant(radius, a, b) {
  const hi = Math.min(a, radius);
  if (hi <= -radius) return 0;
  const S = (x) => chordIntegral(radius, x);
  const full = (lo, up) => (up > lo ? 2 * (S(up) - S(lo)) : 0);
  const partial = (lo, up) => (up > lo ? b * (up - lo) + (S(up) - S(lo)) : 0);

  if (b >= radius) return full(-radius, hi);
  if (b <= -radius) return 0;
  const c = Math.sqrt(radius * radius - b * b);
  if (b >= 0) {
    return full(-radius, Math.min(hi, -c)) + partial(-c, Math.min(hi, c)) + full(c, hi);
  }
  return partial(-c, Math.min(hi, c));
}

export function DiscRectArea(radius, x0, x1, y0, y1) {
  if (radius <= 0 || x1 <= x0 || y1 <= y0) return 0;
  return quadrant(radius, x1, y1) - quadrant(radius, x0, y1) - quadrant(radius, x1, y0) + quadrant(radius, x0, y0);
}

/// The footprint of `radius` texels, as (dx, dy, weight) triples; 0 is one tap
/// of weight 1. (The Gaussian negative control is not ported.)
export function Footprint(radius) {
  const taps = [];
  if (radius < 1e-6) {
    taps.push([0, 0, 1]);
    return taps;
  }
  const reach = Math.ceil(radius + 0.5);
  const weights = [];
  let total = 0;
  for (let j = -reach; j <= reach; j += 1) {
    for (let i = -reach; i <= reach; i += 1) {
      const w = DiscRectArea(radius, i - 0.5, i + 0.5, j - 0.5, j + 0.5);
      if (w <= 0) continue;
      taps.push([i, j, 0]);
      weights.push(w);
      total += w;
    }
  }
  for (let t = 0; t < taps.length; t += 1) taps[t][2] = f(weights[t] / total);
  return taps;
}
