/**
 * Stencil — browser demo.
 *
 * Spray paint through a cut stencil. The one idea, from `source/Stencil.h`: a
 * stencil cannot hold a floating piece — the middle of an O would fall out
 * when cut — so the cutter leaves BRIDGES, thin strips of sheet tying every
 * island to the rest, and then the paint is sprayed through the holes from a
 * distance and creeps under the edges.
 *
 * Like jacquard and toolpath, this plugin is **not only a shader**, and the
 * halves of the page are not equally faithful:
 *
 *   The shaders are the plugin's. The ten bodies below are `source/Shaders.cpp`'s
 *   — the vertex shader, the PCG hash, and detect, blur, seed, flood, second,
 *   spray, settle and composite — spliced in by `demo/tools/sync_shaders.py`
 *   with their tabs and comments, and assembled as `shaders::assemble` and
 *   `assembleHashed` do. `demo/tools/check_shaders.py` compares them character
 *   for character and `tools/verify.sh` runs it. **The jump flood the cutter
 *   asks for is the plugin's own flood shader**, run here in WebGL2 on
 *   RGBA32UI targets, with `Stencil::flood`'s schedule and its region.
 *
 *   The CPU half is a PORT: `cutter.js` is `source/Bridge.cpp` (run labelling
 *   and union-find, the Min Island drop, the passes, the shortest bridge with
 *   its total-order tie-break, last frame's kept bridges, the band), and
 *   `controls.js` is Controls.cpp, Palette.cpp's Ink and Spray.cpp. The frame
 *   sequence below is `Stencil::ProcessOpenGL`'s. Only a reader checks a port;
 *   the one-off comparison against the C++ is recorded in AGENTS.md.
 *
 * ------------------------------------------------------ the readbacks
 *
 * The plugin reads the tone back every frame (`glReadPixels` RED/FLOAT of an
 * RGBA16F target), and every flood pass reads the second seeds back (R32UI).
 * The page does the same: the tone as RGBA/FLOAT (WebGL2 guarantees only that
 * for a float attachment, so four floats a texel and the first kept) and the
 * seconds as RGBA_INTEGER/UNSIGNED_INT (likewise). Same numbers, more bytes;
 * both stall the pipeline where the plugin's do.
 *
 * ------------------------------------------------------- what is missing
 *
 * **Nothing audio**: Stencil has no audio path. **No clock**: the plugin reads
 * no time (SetTimeSupported false), so the page's clock only moves the clip.
 * **The About block is absent**, as on every page in this suite. **Layers is a
 * dropdown**: it is FF_TYPE_INTEGER in the plugin and the kit has no integer
 * control. The Perturb test hooks are at rest (0), as the shipped plugin has
 * them, and are not ported.
 */

import { mountDemo } from './vendor/demo.js';
import { Program, PassBuffer, bindTexture } from './vendor/gl.js';
import * as C from './controls.js';
import * as B from './cutter.js';

//=== BEGIN GENERATED by demo/tools/sync_shaders.py (shaders) from source/Shaders.cpp -- do not edit by hand.
const VERSION = '#version 410 core\n';

const VERTEX_BODY = `
layout( location = 0 ) in vec4 vPosition;
layout( location = 1 ) in vec2 vUV;

out vec2 uv;

void main()
{
	gl_Position = vPosition;
	uv = vUV;
}
`;

const HASH_BODY = `
uint pcg( uint v )
{
	uint state = v * 747796405u + 2891336453u;
	uint word  = ( ( state >> ( ( state >> 28u ) + 4u ) ) ^ state ) * 277803737u;
	return ( word >> 22u ) ^ word;
}

float hash01( uint v )
{
	return float( pcg( v ) >> 8u ) * ( 1.0 / 16777216.0 );
}

float hash2( ivec2 p, uint salt )
{
	return hash01( uint( p.x ) + pcg( uint( p.y ) + pcg( salt ) ) );
}
`;

const DETECT_BODY = `
uniform sampler2D InputTexture;
uniform ivec2 InputSize;//the input's pixels (the content, not the hardware size)
uniform int Scale;      //input pixels to a texel side
uniform int Invert;     //1: paint the light, not the dark

out vec4 fragColor;

void main()
{
	ivec2 base = ivec2( gl_FragCoord.xy ) * Scale;
	ivec2 last = InputSize - ivec2( 1 );
	vec4 sum   = vec4( 0.0 );
	for( int j = 0; j < Scale; ++j )
	{
		for( int i = 0; i < Scale; ++i )
		{
			vec4 c = texelFetch( InputTexture, min( base + ivec2( i, j ), last ), 0 );
			//Un-premultiply for the colour, or a soft alpha edge reads as a
			//darker colour.
			vec3 straight = c.a > 0.0031 ? c.rgb / c.a : c.rgb;
			float luma    = dot( straight, vec3( 0.2126, 0.7152, 0.0722 ) );
			if( Invert != 0 )
				luma = 1.0 - luma;
			//The tone: the clip laid over white paper. A transparent pixel
			//is bare wall, never a hole to paint through, either way round.
			sum += vec4( c.a * luma + ( 1.0 - c.a ), straight );
		}
	}
	fragColor = sum / float( Scale * Scale );
}
`;

const BLUR_BODY = `
uniform sampler2D Value;
uniform ivec2 Axis;  //(1, 0) or (0, 1)
uniform float Sigma; //texels
uniform int Taps;    //each side
uniform int FromCut; //1: blur step( 0.75, value ), the holes of the cut

out vec4 fragColor;

vec4 valueAt( ivec2 q )
{
	vec4 v = texelFetch( Value, q, 0 );
	return FromCut != 0 ? step( vec4( 0.75 ), v ) : v;
}

void main()
{
	ivec2 p    = ivec2( gl_FragCoord.xy );
	ivec2 last = textureSize( Value, 0 ) - ivec2( 1 );
	vec4 sum   = vec4( 0.0 );
	float weights = 0.0;
	for( int k = -Taps; k <= Taps; ++k )
	{
		float w = exp( -0.5 * float( k * k ) / ( Sigma * Sigma ) );
		ivec2 q = p + Axis * k;
		//Past the lattice is the margin: sheet, no hole, for the cut; the
		//edge texel again for the tone.
		if( FromCut != 0 && ( q.x < 0 || q.y < 0 || q.x > last.x || q.y > last.y ) )
		{
			weights += w;
			continue;
		}
		sum += w * valueAt( clamp( q, ivec2( 0 ), last ) );
		weights += w;
	}
	fragColor = sum / weights;
}
`;

const SEED_BODY = `
uniform usampler2D Labels;//0 hole, else the piece's label

out uvec4 fragSeeds;

const uint NONE = 0xffffffffu;

void main()
{
	ivec2 p = ivec2( gl_FragCoord.xy );
	uint l  = texelFetch( Labels, p, 0 ).r;
	fragSeeds = l != 0u ? uvec4( uint( p.x ) | ( uint( p.y ) << 16 ), l, NONE, 0u ) : uvec4( NONE, 0u, NONE, 0u );
}
`;

const FLOOD_BODY = `
uniform usampler2D Seeds;//RGBA32UI: first (position, piece), second (position, piece)
uniform int Step;
uniform ivec4 Region;    //the cells flooded, [x, z) x [y, w): nothing outside is read

out uvec4 fragSeeds;

const uint NONE = 0xffffffffu;
const int FAR   = 0x7fffffff;

ivec2 p;
uint firstSeed;
int firstDist;
uint firstLabel;
uint secondSeed;
int secondDist;
uint secondLabel;

ivec2 unpack( uint s )
{
	return ivec2( int( s & 0xffffu ), int( s >> 16 ) );
}

int distanceTo( uint s )
{
	if( s == NONE )
		return FAR;
	ivec2 v = unpack( s ) - p;
	return v.x * v.x + v.y * v.y;
}

//Is (d, s) nearer than (dRef, sRef)? Ties by y, then x: the packed position
//IS (y, x) in order, y in the high half.
bool nearer( int d, uint s, int dRef, uint sRef )
{
	if( d != dRef )
		return d < dRef;
	return s < sRef;
}

void consider( uint s, uint l )
{
	if( s == NONE || l == 0u )
		return;
	int d = distanceTo( s );
	if( nearer( d, s, firstDist, firstSeed ) )
	{
		//The old first becomes the second if it is another piece's: it is
		//then nearer than any second of that piece's own could be.
		if( l != firstLabel && firstLabel != 0u )
		{
			secondSeed  = firstSeed;
			secondDist  = firstDist;
			secondLabel = firstLabel;
		}
		firstSeed  = s;
		firstDist  = d;
		firstLabel = l;
	}
	else if( l != firstLabel && nearer( d, s, secondDist, secondSeed ) )
	{
		secondSeed  = s;
		secondDist  = d;
		secondLabel = l;
	}
}

void main()
{
	p           = ivec2( gl_FragCoord.xy );
	uvec4 own   = texelFetch( Seeds, p, 0 );
	firstSeed   = own.x;
	firstLabel  = own.y;
	firstDist   = distanceTo( own.x );
	secondSeed  = own.z;
	secondLabel = own.w;
	secondDist  = distanceTo( own.z );

	for( int dy = -1; dy <= 1; ++dy )
	{
		for( int dx = -1; dx <= 1; ++dx )
		{
			if( dx == 0 && dy == 0 )
				continue;
			ivec2 q = p + ivec2( dx, dy ) * Step;
			if( q.x < Region.x || q.y < Region.y || q.x >= Region.z || q.y >= Region.w )
				continue;
			uvec4 c = texelFetch( Seeds, q, 0 );
			consider( c.x, c.y );
			consider( c.z, c.w );
		}
	}
	fragSeeds = uvec4( firstSeed, firstLabel, secondSeed, secondLabel );
}
`;

const SECOND_BODY = `
uniform usampler2D Seeds;

out uvec4 fragSecond;

void main()
{
	fragSecond = uvec4( texelFetch( Seeds, ivec2( gl_FragCoord.xy ), 0 ).z, 0u, 0u, 0u );
}
`;

const SPRAY_BODY = `
uniform sampler2D Cut; //RGBA8: 0 sheet, 0.5 bridge, 1 hole, a layer a channel
uniform sampler2D Taps;//RGBA32F, TapCount x 1: (dx, dy, weight, 0)
uniform int TapCount;

out vec4 fragColor;

void main()
{
	ivec2 p    = ivec2( gl_FragCoord.xy );
	ivec2 size = textureSize( Cut, 0 );
	vec4 sum   = vec4( 0.0 );
	for( int t = 0; t < TapCount; ++t )
	{
		vec4 tap = texelFetch( Taps, ivec2( t, 0 ), 0 );
		ivec2 q  = p + ivec2( tap.xy );
		if( q.x < 0 || q.y < 0 || q.x >= size.x || q.y >= size.y )
			continue;
		sum += tap.z * step( vec4( 0.75 ), texelFetch( Cut, q, 0 ) );
	}
	fragColor = sum;
}
`;

const SETTLE_BODY = `
uniform sampler2D Cut;
uniform sampler2D Sprayed;
uniform sampler2D Creep;
uniform int UseCreep;
uniform float Pressure;
uniform float LiftAmount;
uniform float BridgeLift;
uniform float SheetLift;
uniform float Saturation;
uniform int DripReach;   //texels, the longest a drip can run
uniform float DripChance;//share of columns that run
uniform int Layers;

out vec4 fragColor;

vec4 landed( ivec2 q )
{
	vec4 cut    = texelFetch( Cut, q, 0 );
	vec4 hole   = step( vec4( 0.75 ), cut );
	vec4 bridge = step( vec4( 0.25 ), cut ) * ( vec4( 1.0 ) - hole );
	vec4 lifted = mix( vec4( SheetLift ), vec4( BridgeLift ), bridge ) * ( vec4( 1.0 ) - hole );
	vec4 creep  = UseCreep != 0 ? LiftAmount * lifted * texelFetch( Creep, q, 0 ) : vec4( 0.0 );
	return Pressure * ( texelFetch( Sprayed, q, 0 ) + creep );
}

void main()
{
	ivec2 p    = ivec2( gl_FragCoord.xy );
	ivec2 size = textureSize( Cut, 0 );
	vec4 paint = landed( p );

	vec4 live = vec4( 0.0 );
	for( int c = 0; c < 4; ++c )
		live[ c ] = c < Layers ? 1.0 : 0.0;

	vec4 drip = vec4( 0.0 );
	if( DripReach > 0 && DripChance > 0.0 )
	{
		vec4 runs = vec4( 0.0 ), reach = vec4( 0.0 );
		for( int c = 0; c < 4; ++c )
		{
			runs[ c ]  = hash2( ivec2( p.x, c ), 17u ) < DripChance ? 1.0 : 0.0;
			reach[ c ] = float( DripReach ) * ( 0.35 + 0.65 * hash2( ivec2( p.x, c ), 29u ) );
		}
		runs *= live;
		if( dot( runs, runs ) > 0.0 )
		{
			for( int j = 1; j <= DripReach; ++j )
			{
				ivec2 q = p + ivec2( 0, j );
				if( q.y >= size.y )
					break;
				vec4 over = max( landed( q ) - vec4( Saturation ), vec4( 0.0 ) );
				//How far this source's excess runs: a full run at 0.3 over.
				vec4 run  = reach * min( over / 0.3, vec4( 1.0 ) );
				vec4 t    = vec4( float( j ) ) / max( run, vec4( 1.0e-3 ) );
				vec4 here = step( vec4( float( j ) ), run ) * ( vec4( 1.0 ) - 0.5 * t * t );
				drip      = max( drip, runs * here );
			}
		}
	}
	fragColor = max( min( paint, vec4( 1.0 ) ), drip ) * live;
}
`;

const COMPOSITE_BODY = `
uniform sampler2D InputTexture;
uniform vec2 MaxUV;
uniform sampler2D Coverage; //lattice, a layer a channel
uniform vec2 LatticeUV;     //the job's 0..1 on the lattice's 0..1
uniform int Layers;
uniform vec3 Ink[ 4 ];      //lightest first
uniform int Order;          //0 lightest first (the plugin); 1 the other way (a test hook)
uniform int Wall;           //0 clip, 1 brick, 2 concrete, 3 plain
uniform vec3 PlainWall;
uniform vec2 OutSize;
uniform float MixAmount;

in vec2 uv;
out vec4 fragColor;

//Value noise on a lattice of \`cell\` frame heights: smooth, raster-free.
float valueNoise( vec2 q, float cell, uint salt )
{
	vec2 g  = q / cell;
	ivec2 i = ivec2( floor( g ) );
	vec2 f  = g - floor( g );
	f       = f * f * ( 3.0 - 2.0 * f );
	float a = hash2( i, salt ), b = hash2( i + ivec2( 1, 0 ), salt );
	float c = hash2( i + ivec2( 0, 1 ), salt ), d = hash2( i + ivec2( 1, 1 ), salt );
	return mix( mix( a, b, f.x ), mix( c, d, f.x ), f.y );
}

vec3 brick( vec2 q )
{
	//Courses 5% of the frame high, bricks 2.2 courses long, stretcher bond.
	float course = 0.05;
	float row    = floor( q.y / course );
	float span   = 0.11;
	float shift  = mod( row, 2.0 ) * 0.5 * span;
	float col    = floor( ( q.x + shift ) / span );
	vec2 local   = vec2( q.x + shift - col * span, q.y - row * course );
	float mortar = 0.0045;
	float edge   = min( min( local.x, span - local.x ), min( local.y, course - local.y ) );
	float joint  = 1.0 - smoothstep( 0.5 * mortar, 0.5 * mortar + 0.0015, edge );

	ivec2 id   = ivec2( int( col ), int( row ) );
	float tint = hash2( id, 5u );
	vec3 clay  = mix( vec3( 0.52, 0.22, 0.15 ), vec3( 0.66, 0.36, 0.24 ), tint );
	clay      *= 0.86 + 0.14 * hash2( id, 9u );
	float grain = valueNoise( q, 0.004, 11u ) * 0.6 + valueNoise( q, 0.015, 13u ) * 0.4;
	clay       *= 0.88 + 0.24 * grain;
	vec3 mortarColour = vec3( 0.63, 0.61, 0.57 ) * ( 0.9 + 0.2 * valueNoise( q, 0.003, 15u ) );
	return mix( clay, mortarColour, joint );
}

vec3 concrete( vec2 q )
{
	float broad = valueNoise( q, 0.12, 21u );
	float mid   = valueNoise( q, 0.025, 23u );
	float fine  = valueNoise( q, 0.004, 25u );
	float v     = 0.60 + 0.07 * ( broad - 0.5 ) + 0.06 * ( mid - 0.5 ) + 0.08 * ( fine - 0.5 );
	//Pits: a few cells of a fine lattice are small dark holes.
	vec2 g    = q / 0.006;
	ivec2 id  = ivec2( floor( g ) );
	float pit = hash2( id, 27u ) < 0.04 ? 1.0 - smoothstep( 0.12, 0.28, length( g - floor( g ) - vec2( 0.5 ) ) ) : 0.0;
	v        *= 1.0 - 0.35 * pit;
	return vec3( v, v * 0.99, v * 0.955 );
}

void main()
{
	vec4 clip = texture( InputTexture, uv * MaxUV );
	vec2 q    = gl_FragCoord.xy / OutSize.y;//frame heights

	vec3 rgb;
	float alpha = 1.0;
	if( Wall == 0 )
	{
		rgb   = clip.rgb;//premultiplied, as it came
		alpha = clip.a;
	}
	else if( Wall == 1 )
		rgb = brick( q );
	else if( Wall == 2 )
		rgb = concrete( q );
	else
		rgb = PlainWall;

	vec4 cover = texture( Coverage, uv * LatticeUV );
	for( int n = 0; n < 4; ++n )
	{
		if( n >= Layers )
			break;
		int layer = Order == 0 ? n : Layers - 1 - n;
		float c   = clamp( cover[ layer ], 0.0, 1.0 );
		//Paint over, premultiplied: opaque where it lands.
		rgb   = rgb * ( 1.0 - c ) + Ink[ layer ] * c;
		alpha = alpha * ( 1.0 - c ) + c;
	}

	vec4 effect = vec4( rgb, alpha );
	fragColor   = MixAmount >= 1.0 ? effect : mix( clip, effect, MixAmount );
}
`;
//=== END GENERATED (shaders)

/// shaders::assemble and assembleHashed.
const assemble = (body) => VERSION + body;
const assembleHashed = (body) => VERSION + HASH_BODY + body;

//===========================================================================
// The renderer: Stencil::ProcessOpenGL, in its order.
//
//   1, 2  detect and smooth on the lattice; read the tone back
//   3, 4  per layer: threshold, drop, bridge -- cutter.js, the flood on the GPU
//   5     spray through the holes, the footprint's exact taps
//   6     creep under lifted edges
//   7     settle: what lands, and the drips
//   8     composite, onto the canvas
//===========================================================================

const S = C.STENCIL_H;
const K_MAX_LAYERS = C.CONTROLS_H.kMaxLayers;

/// Stencil::LatticeScale.
const latticeScale = (height) => Math.max(1, Math.floor((height + S.kLatticeLines - 1) / S.kLatticeLines));

/// The Gaussian's taps each side for a sigma, capped (Stencil.cpp's tapsFor).
const tapsFor = (sigma) => Math.min(48, Math.ceil(Math.fround(3 * sigma)));

/// What the line under the canvas reports. Filled by the renderer.
const telemetry = { lattice: '', layers: 0, islands: 0, dropped: 0, bridges: 0, kept: 0, passes: 0, floating: 0, cpuMillis: 0, floodMillis: 0 };

/// Driven checks only (see AGENTS.md, "The browser demo"): `fresh()` forgets
/// last frame's bridges, as a new instance would; `flood`, if set, replaces the
/// GPU flood (the check hands in an exact one); `lastGrids` are the cut grids,
/// `lastTone` the tone read back, `lastResults` what the cutter did;
/// `afterRender(gl, input)` is called before the frame is presented.
const hooks = { afterRender: null, fresh: null, flood: null, lastGrids: null, lastTone: null, lastResults: null, lastInput: null, lastSettings: null, lastHistory: null };

function createRenderer(gl, quad) {
  const vertex = assemble(VERTEX_BODY);
  const detectShader = new Program(gl, vertex, assemble(DETECT_BODY), 'detect');
  const blurShader = new Program(gl, vertex, assemble(BLUR_BODY), 'blur');
  const seedShader = new Program(gl, vertex, assemble(SEED_BODY), 'seed');
  const floodShader = new Program(gl, vertex, assemble(FLOOD_BODY), 'flood');
  const secondShader = new Program(gl, vertex, assemble(SECOND_BODY), 'second');
  const sprayShader = new Program(gl, vertex, assemble(SPRAY_BODY), 'spray');
  const settleShader = new Program(gl, vertex, assembleHashed(SETTLE_BODY), 'settle');
  const compositeShader = new Program(gl, vertex, assembleHashed(COMPOSITE_BODY), 'composite');

  const nearest = { filter: 'nearest' };
  const tone = [new PassBuffer(gl, nearest), new PassBuffer(gl, nearest)];
  const labels = new PassBuffer(gl, nearest);
  const seeds = [new PassBuffer(gl, nearest), new PassBuffer(gl, nearest)];
  const seconds = new PassBuffer(gl, nearest);
  const cut = new PassBuffer(gl, nearest);
  const sprayed = new PassBuffer(gl, nearest);
  const creep = [new PassBuffer(gl, nearest), new PassBuffer(gl, nearest)];
  const coverage = new PassBuffer(gl, { filter: 'linear' });

  // The footprint's taps, RGBA32F N x 1; never rendered to.
  const taps = gl.createTexture();
  let tapRadius = -1;
  let tapCount = 0;

  // The state across frames: last frame's bridges per layer, in 0..1 of the
  // lattice so a resize carries them.
  let history = [[], [], [], []];
  hooks.fresh = () => {
    history = [[], [], [], []];
  };

  let toneRGBA = new Float32Array(0);
  let regionValues = new Uint32Array(0);
  let cutValues = new Uint8Array(0);
  let floodMillis = 0;

  //-------------------------------------------------------------------------
  // Stencil::flood: upload the labels, seed, jump-flood with two seeds a
  // texel, read the seconds back. The plugin's own shaders and schedule.
  //-------------------------------------------------------------------------
  function gpuFlood(pieceLabels, width, height, region, second) {
    const started = performance.now();
    if (labels.width !== width || labels.height !== height || !seeds[0].texture) return null;
    gl.bindTexture(gl.TEXTURE_2D, labels.texture);
    gl.pixelStorei(gl.UNPACK_ALIGNMENT, 4);
    gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, width, height, gl.RED_INTEGER, gl.UNSIGNED_INT, pieceLabels);
    gl.bindTexture(gl.TEXTURE_2D, null);

    // 1. seed
    seeds[0].bind();
    seedShader.use();
    bindTexture(gl, 0, labels.texture);
    seedShader.setSampler('Labels', 0);
    quad.draw();

    // 2. flood: the step-1 pass first, the halving sequence from under the
    // longer side, then a finishing run of halving steps from 1/128 of it.
    const rw = region.x1 - region.x0;
    const rh = region.y1 - region.y0;
    if (rw <= 0 || rh <= 0) return null;
    const steps = [1];
    let longest = 1;
    while (longest < Math.max(rw, rh)) longest *= 2;
    for (let step = longest / 2; step >= 1; step = Math.floor(step / 2)) steps.push(step);
    for (let step = Math.max(2, Math.floor(longest / 128)); step >= 1; step = Math.floor(step / 2)) steps.push(step);

    floodShader.use();
    floodShader.setSampler('Seeds', 0);
    gl.uniform4i(floodShader.location('Region'), region.x0, region.y0, region.x1, region.y1);
    // The viewport, not a scissor, confines the draws to the region.
    let current = 0;
    for (const step of steps) {
      seeds[1 - current].bind();
      gl.viewport(region.x0, region.y0, rw, rh);
      bindTexture(gl, 0, seeds[current].texture);
      floodShader.setInt('Step', step);
      quad.draw();
      current = 1 - current;
    }

    // 3. the seconds alone, and read them back
    seconds.bind();
    gl.viewport(region.x0, region.y0, rw, rh);
    secondShader.use();
    bindTexture(gl, 0, seeds[current].texture);
    secondShader.setSampler('Seeds', 0);
    quad.draw();

    // WebGL2 guarantees RGBA_INTEGER / UNSIGNED_INT for an unsigned integer
    // attachment, so four values a cell, the first kept.
    if (regionValues.length < rw * rh * 4) regionValues = new Uint32Array(rw * rh * 4);
    gl.pixelStorei(gl.PACK_ALIGNMENT, 4);
    gl.readPixels(region.x0, region.y0, rw, rh, gl.RGBA_INTEGER, gl.UNSIGNED_INT, regionValues);
    // second.resize( w * h, kNone ): what was outside the region is kept.
    if (second === null || second.length !== width * height) second = new Uint32Array(width * height).fill(B.kNone);
    for (let y = 0; y < rh; y += 1) {
      const row = (region.y0 + y) * width + region.x0;
      for (let x = 0; x < rw; x += 1) second[row + x] = regionValues[(y * rw + x) * 4];
    }
    bindTexture(gl, 0, null);
    floodMillis += performance.now() - started;
    return second;
  }

  return {
    render({ input, params, width: vpW, height: vpH }) {
      // The host stores every parameter as a float.
      const p = (id) => Math.fround(params.get(id));
      const width = input.width;
      const height = input.height;
      hooks.lastInput = input;

      // A resize keeps last frame's bridges (they are in 0..1 of the lattice);
      // only the kPerturbResizeClears test hook would forget them.

      //------------------------------------------------------------------
      // What the controls say, in lattice texels.
      //------------------------------------------------------------------
      const k = latticeScale(height);
      const lw = Math.floor((width + k - 1) / k);
      const lh = Math.floor((height + k - 1) / k);
      const gw = lw + 2;
      const gh = lh + 2;
      const texelsPerHeight = height / k;
      const f = Math.fround;

      const layers = C.LayerCount(layersValue(p('layers')));
      const threshold = f(Math.min(Math.max(p('threshold'), 0), 1));
      const smooth = f(C.SmoothSigmaHeights(p('smooth')) * f(texelsPerHeight));
      const bridgeW = C.BridgeWidthHeights(p('bridgeWidth')) * texelsPerHeight;
      const minSide = C.MinIslandSideHeights(p('minIsland')) * texelsPerHeight;
      const radius = C.FootprintRadiusHeights(p('distance')) * texelsPerHeight;
      const pressure = C.PressureAmount(p('pressure'));
      const liftAmount = C.LiftAmount(p('lift'));
      const liftSigma = f(C.LiftSigmaHeights(p('lift')) * f(texelsPerHeight));
      const dripReach = Math.round(C.DripLengthHeights(p('drips')) * texelsPerHeight);
      const dripChance = C.DripChance(p('drips'));
      const paletteIndex = C.OptionIndex(p('palette'), C.CONTROLS_H.kPaletteCount);
      const fromClip = C.OptionIndex(p('layerColours'), C.CONTROLS_H.kLayerColoursCount) === C.kLayerColours.kFromClip;
      const wall = C.OptionIndex(p('wall'), C.CONTROLS_H.kWallCount);
      const useCreep = liftAmount > 0 && liftSigma >= f(0.3);

      //------------------------------------------------------------------
      // Every buffer.
      //------------------------------------------------------------------
      if (Math.abs(radius - tapRadius) > 1e-9) {
        const footprint = C.Footprint(radius);
        const data = new Float32Array(footprint.length * 4);
        footprint.forEach((t, i) => data.set([t[0], t[1], t[2], 0], i * 4));
        tapCount = footprint.length;
        gl.bindTexture(gl.TEXTURE_2D, taps);
        gl.pixelStorei(gl.UNPACK_ALIGNMENT, 4);
        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA32F, tapCount, 1, 0, gl.RGBA, gl.FLOAT, data);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
        gl.bindTexture(gl.TEXTURE_2D, null);
        tapRadius = radius;
      }

      tone[0].ensure(lw, lh, gl.RGBA16F);
      tone[1].ensure(lw, lh, gl.RGBA16F);
      labels.ensure(gw, gh, gl.R32UI);
      seeds[0].ensure(gw, gh, gl.RGBA32UI);
      seeds[1].ensure(gw, gh, gl.RGBA32UI);
      seconds.ensure(gw, gh, gl.R32UI);
      cut.ensure(lw, lh, gl.RGBA8);
      sprayed.ensure(lw, lh, gl.RGBA16F);
      creep[0].ensure(lw, lh, gl.RGBA16F);
      creep[1].ensure(lw, lh, gl.RGBA16F);
      coverage.ensure(lw, lh, gl.RGBA16F);
      gl.disable(gl.BLEND);

      //------------------------------------------------------------------
      // 1, 2. detect and smooth, on the lattice; read the tone back.
      //------------------------------------------------------------------
      tone[0].bind();
      detectShader.use();
      bindTexture(gl, 0, input.texture);
      detectShader.setSampler('InputTexture', 0);
      gl.uniform2i(detectShader.location('InputSize'), width, height);
      detectShader.setInt('Scale', k);
      detectShader.setInt('Invert', p('invert') > 0.5 ? 1 : 0);
      quad.draw();

      if (smooth >= f(0.3)) {
        blurShader.use();
        blurShader.setSampler('Value', 0);
        blurShader.set('Sigma', smooth);
        blurShader.setInt('Taps', tapsFor(smooth));
        blurShader.setInt('FromCut', 0);
        for (let axis = 0; axis < 2; axis += 1) {
          tone[1 - axis].bind();
          bindTexture(gl, 0, tone[axis].texture);
          gl.uniform2i(blurShader.location('Axis'), axis === 0 ? 1 : 0, axis === 0 ? 0 : 1);
          quad.draw();
        }
        bindTexture(gl, 0, null);
      }

      tone[0].bind();
      if (toneRGBA.length !== lw * lh * 4) toneRGBA = new Float32Array(lw * lh * 4);
      gl.pixelStorei(gl.PACK_ALIGNMENT, 4);
      gl.readPixels(0, 0, lw, lh, gl.RGBA, gl.FLOAT, toneRGBA);
      hooks.lastTone = { values: toneRGBA, width: lw, height: lh };

      //------------------------------------------------------------------
      // 3, 4. the cutter, a layer at a time.
      //------------------------------------------------------------------
      const started = performance.now();
      floodMillis = 0;
      const settings = { width: bridgeW, minIslandArea: minSide * minSide, keepSlack: S.kKeepSlack, keepRadius: S.kKeepRadius, maxPasses: 32 };
      const flood = hooks.flood ?? gpuFlood;

      if (cutValues.length !== lw * lh * 4) cutValues = new Uint8Array(lw * lh * 4);
      cutValues.fill(0);
      const grids = [];
      const results = [];
      const keptIn = [];
      for (let layer = 1; layer <= layers; layer += 1) {
        const cutAt = C.LayerThreshold(threshold, layer, layers);
        const grid = { width: gw, height: gh, cells: new Uint8Array(gw * gh).fill(B.kSheet) };
        for (let y = 0; y < lh; y += 1) {
          for (let x = 0; x < lw; x += 1) {
            if (toneRGBA[(y * lw + x) * 4] < cutAt) grid.cells[(y + 1) * gw + x + 1] = B.kHole;
          }
        }

        // Last frame's bridges, from 0..1 of the lattice into this grid.
        const kept = history[layer - 1].map((old) => ({
          ax: Math.floor(old.ax * lw) + 1,
          ay: Math.floor(old.ay * lh) + 1,
          bx: Math.floor(old.bx * lw) + 1,
          by: Math.floor(old.by * lh) + 1,
        }));
        keptIn.push(kept);

        const r = B.Cut(grid, settings, kept, flood);
        grids.push(grid);
        results.push(r);

        history[layer - 1] = r.bridges.map((b) => ({
          ax: (b.ax - 1 + 0.5) / lw,
          ay: (b.ay - 1 + 0.5) / lh,
          bx: (b.bx - 1 + 0.5) / lw,
          by: (b.by - 1 + 0.5) / lh,
        }));

        for (let y = 0; y < lh; y += 1) {
          for (let x = 0; x < lw; x += 1) {
            const c = grid.cells[(y + 1) * gw + x + 1];
            cutValues[(y * lw + x) * 4 + (layer - 1)] = c === B.kHole ? 255 : c === B.kBridge ? 128 : 0;
          }
        }
      }
      for (let layer = layers + 1; layer <= K_MAX_LAYERS; layer += 1) history[layer - 1] = [];
      hooks.lastGrids = grids;
      hooks.lastResults = results;
      hooks.lastSettings = settings;
      hooks.lastHistory = keptIn;

      gl.bindTexture(gl.TEXTURE_2D, cut.texture);
      gl.pixelStorei(gl.UNPACK_ALIGNMENT, 4);
      gl.texSubImage2D(gl.TEXTURE_2D, 0, 0, 0, lw, lh, gl.RGBA, gl.UNSIGNED_BYTE, cutValues);
      gl.bindTexture(gl.TEXTURE_2D, null);

      //------------------------------------------------------------------
      // The inks: the palette's, or the clip's own mean colour over each
      // layer's band of tone.
      //------------------------------------------------------------------
      const inks = new Float32Array(K_MAX_LAYERS * 3);
      for (let layer = 1; layer <= K_MAX_LAYERS; layer += 1) {
        const c = C.Ink(paletteIndex, Math.min(layer, layers), layers);
        inks.set(c, (layer - 1) * 3);
      }
      if (fromClip) {
        const sum = [[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]];
        const count = [0, 0, 0, 0];
        const cuts = [];
        for (let layer = 1; layer <= layers; layer += 1) cuts[layer] = C.LayerThreshold(threshold, layer, layers);
        for (let i = 0, n = lw * lh; i < n; i += 1) {
          const v = toneRGBA[4 * i];
          let band = 0;
          for (let layer = layers; layer >= 1; layer -= 1) {
            if (v < cuts[layer]) {
              band = layer;
              break;
            }
          }
          if (band === 0) continue;
          for (let c = 0; c < 3; c += 1) sum[band - 1][c] += toneRGBA[4 * i + 1 + c];
          count[band - 1] += 1;
        }
        for (let layer = 1; layer <= layers; layer += 1) {
          if (count[layer - 1] > 0) for (let c = 0; c < 3; c += 1) inks[(layer - 1) * 3 + c] = sum[layer - 1][c] / count[layer - 1];
        }
      }

      const cpuTotal = performance.now() - started;
      telemetry.lattice = `${lw} × ${lh}`;
      telemetry.layers = layers;
      telemetry.islands = results.reduce((a, r) => a + r.islands, 0);
      telemetry.dropped = results.reduce((a, r) => a + r.dropped, 0);
      telemetry.bridges = results.reduce((a, r) => a + r.bridges.length, 0);
      telemetry.kept = results.reduce((a, r) => a + r.bridges.filter((b) => b.kept).length, 0);
      telemetry.passes = results.reduce((a, r) => Math.max(a, r.passes), 0);
      telemetry.floating = results.reduce((a, r) => a + Math.max(0, r.floatingLeft), 0);
      telemetry.floodMillis = floodMillis;
      telemetry.cpuMillis = cpuTotal - floodMillis;

      //------------------------------------------------------------------
      // 5. spray through the holes.
      //------------------------------------------------------------------
      sprayed.bind();
      sprayShader.use();
      bindTexture(gl, 0, cut.texture);
      bindTexture(gl, 1, taps);
      sprayShader.setSampler('Cut', 0);
      sprayShader.setSampler('Taps', 1);
      sprayShader.setInt('TapCount', tapCount);
      quad.draw();
      bindTexture(gl, 1, null);

      //------------------------------------------------------------------
      // 6. creep under lifted edges: a Gaussian of the holes.
      //------------------------------------------------------------------
      if (useCreep) {
        blurShader.use();
        blurShader.setSampler('Value', 0);
        blurShader.set('Sigma', liftSigma);
        blurShader.setInt('Taps', tapsFor(liftSigma));

        creep[1].bind();
        bindTexture(gl, 0, cut.texture);
        blurShader.setInt('FromCut', 1);
        gl.uniform2i(blurShader.location('Axis'), 1, 0);
        quad.draw();

        creep[0].bind();
        bindTexture(gl, 0, creep[1].texture);
        blurShader.setInt('FromCut', 0);
        gl.uniform2i(blurShader.location('Axis'), 0, 1);
        quad.draw();
        bindTexture(gl, 0, null);
      }

      //------------------------------------------------------------------
      // 7. settle: what lands, and the drips.
      //------------------------------------------------------------------
      coverage.bind();
      settleShader.use();
      bindTexture(gl, 0, cut.texture);
      bindTexture(gl, 1, sprayed.texture);
      bindTexture(gl, 2, creep[0].texture);
      settleShader.setSampler('Cut', 0);
      settleShader.setSampler('Sprayed', 1);
      settleShader.setSampler('Creep', 2);
      settleShader.setInt('UseCreep', useCreep ? 1 : 0);
      settleShader.set('Pressure', pressure);
      settleShader.set('LiftAmount', liftAmount);
      settleShader.set('BridgeLift', C.CONTROLS_H.kBridgeLift);
      settleShader.set('SheetLift', C.CONTROLS_H.kSheetLift);
      settleShader.set('Saturation', C.CONTROLS_H.kSaturation);
      settleShader.setInt('DripReach', dripReach);
      settleShader.set('DripChance', dripChance);
      settleShader.setInt('Layers', layers);
      quad.draw();

      //------------------------------------------------------------------
      // 8. the composite, onto the canvas. The host's viewport is the canvas.
      //------------------------------------------------------------------
      gl.bindFramebuffer(gl.FRAMEBUFFER, null);
      gl.viewport(0, 0, vpW, vpH);

      compositeShader.use();
      bindTexture(gl, 0, input.texture);
      bindTexture(gl, 1, coverage.texture);
      bindTexture(gl, 2, null);
      compositeShader.setSampler('InputTexture', 0);
      compositeShader.setSampler('Coverage', 1);
      compositeShader.set('MaxUV', 1.0, 1.0);
      compositeShader.set('LatticeUV', width / (k * lw), height / (k * lh));
      compositeShader.setInt('Layers', layers);
      compositeShader.setArray('Ink', inks, 3);
      compositeShader.setInt('Order', 0);
      compositeShader.setInt('Wall', wall);
      compositeShader.set('PlainWall', C.PLAIN_WALL[0], C.PLAIN_WALL[1], C.PLAIN_WALL[2]);
      compositeShader.set('OutSize', width, height);
      compositeShader.set('MixAmount', Math.min(Math.max(p('mix'), 0), 1));
      quad.draw();

      if (hooks.afterRender) hooks.afterRender(gl, input);

      for (let unit = 2; unit >= 0; unit -= 1) bindTexture(gl, unit, null);
    },
  };
}

//===========================================================================
// The controls, read out of Stencil::Stencil(). Same names, same groups, same
// order, same defaults, same dropdown elements. Absent: the About block.
//===========================================================================

/// Layers is FF_TYPE_INTEGER, 1 to 4, exempt from the 0..1 clamp. The kit has
/// no integer control, so -- as jacquard, teletext and copperlist did -- it is
/// a dropdown of every value in the plugin's range, and this turns the
/// dropdown's index back into the count.
const LAYER_ELEMENTS = [];
for (let v = C.CONTROLS_H.kMinLayers; v <= C.CONTROLS_H.kMaxLayers; v += 1) LAYER_ELEMENTS.push(String(v));
function layersValue(index) {
  return C.CONTROLS_H.kMinLayers + Math.round(index);
}

const std = (id, name, def, group, extra = {}) => ({ id, name, type: 'standard', default: def, group, ...extra });
const opt = (id, name, elements, def, group, hint) => ({ id, name, type: 'option', elements, default: def, group, hint });
const bool = (id, name, def, group, hint) => ({ id, name, type: 'boolean', default: def, group, hint });
/// Lengths are in frame heights (Controls.h); shown as a percentage of the height.
const pct = (v) => `${(v * 100).toFixed(2)}%`;

const demo = mountDemo({
  name: 'Stencil',
  pluginId: 'SN01',
  kind: 'effect',
  tagline:
    'Spray paint through a cut stencil. The clip’s tone is cut into one to four layers; a stencil cannot hold a floating piece, so every island of sheet — the middle of an O, a highlight inside a shadow — is tied to the rest by the shortest bridge a distance transform finds. Then the paint is sprayed through the holes from a distance, and creeps under the edges. The shaders here are the plugin’s own, the jump flood included; the cutter is a port of its C++.',
  repo: 'https://github.com/stoatworks-labs/stencil',
  page: 'https://stoatworks-labs.com/software/stencil/',

  // The stock sentence says "same maths", which is only half true here: the
  // shaders are the plugin's, the cutter between them is a port.
  blurb:
    'It is Stencil’s own GLSL, ported from the repository to WebGL2 — the jump flood that measures every bridge included — with the CPU half, the union-find cutter that finds the islands and chooses the bridges, ported to JavaScript by hand; nothing checks that port but a reader. It runs on generated clips in this page, with the plugin’s own parameters and no install.',

  // The tone, the spray and the coverage are RGBA16F and the tone is read back
  // as floats, as the plugin's are.
  needFloat: true,
  // Wall = Clip keeps the clip's alpha where no paint landed.
  showBackdrop: true,

  params: [
    opt('layers', 'Layers', LAYER_ELEMENTS, 2 - C.CONTROLS_H.kMinLayers, 'Cut',
      'Thresholds, 1 to 4, one stencil each, sprayed lightest first so dark lands over light. An integer in the plugin; a dropdown here.'),
    std('threshold', 'Threshold', 0.5, 'Cut', {
      hint: 'The lightest cut, as a tone (the clip’s luma over white paper). Layer k of n paints where the tone is under Threshold × (n − k + 1) / n.',
    }),
    bool('invert', 'Invert', 0, 'Cut', 'Paint the light, not the dark. A transparent pixel is bare wall either way.'),
    std('smooth', 'Smooth', 0.3, 'Cut', {
      display: (v) => `σ ${pct(C.SmoothSigmaHeights(Math.fround(v)))}`,
      hint: 'A Gaussian on the tone before it is cut, sigma 0 to 1% of the frame height.',
    }),
    std('bridgeWidth', 'Bridge Width', C.BridgeWidthParam(0.005), 'Cut', {
      display: (v) => pct(C.BridgeWidthHeights(Math.fround(v))),
      hint: '0.1% to 2% of the frame height, geometric. Never thinner than 4-connected.',
    }),
    std('minIsland', 'Min Island', C.MinIslandParam(0.012), 'Cut', {
      display: (v) => `${pct(C.MinIslandSideHeights(Math.fround(v)))}`,
      hint: 'An island smaller than this side squared is not bridged but dropped: it falls out and is painted. 0 to 5% of the frame height.',
    }),

    std('distance', 'Distance', C.DistanceParam(0.003), 'Spray', {
      display: (v) => `${pct(C.FootprintRadiusHeights(Math.fround(v)))}`,
      hint: 'How far the nozzle is from the wall, as the radius of the cone’s footprint through a hole’s edge: 0 to 2% of the frame height. The halo’s width is proportional to it.',
    }),
    std('pressure', 'Pressure', 0.56, 'Spray', {
      display: (v) => `${C.PressureAmount(Math.fround(v)).toFixed(2)} ×`,
      hint: 'Paint laid per unit of coverage, 0 to 2. Over 0.9 it runs as drips.',
    }),
    std('lift', 'Lift', 0.3, 'Spray', {
      hint: 'How far the sheet stands off the wall: paint creeps under every edge, most under a bridge. σ up to 0.8% of the frame height.',
    }),
    std('drips', 'Drips', 0.4, 'Spray', {
      hint: 'The share of columns under saturated paint that run (up to 45%), and how far (up to 12% of the frame height). Static: nothing reads the clock.',
    }),

    opt('palette', 'Palette', C.PALETTE_NAMES, C.kPalette.kMono, 'Paint',
      'Four cans each; n layers take the darkest n, so one layer is always the darkest can.'),
    opt('layerColours', 'Layer Colours', C.LAYER_COLOURS_NAMES, C.kLayerColours.kFromPalette, 'Paint',
      'From Clip: each layer’s ink is the clip’s mean colour over its band of tone.'),
    opt('wall', 'Wall', C.WALL_NAMES, C.kWall.kWallConcrete, 'Paint',
      'What the paint lands on. Clip keeps the clip (and its alpha) where no paint landed.'),
    std('mix', 'Mix', 1.0, 'Paint'),
  ],

  // The geometry card's rings and the lights on black are islands inside
  // paint: what a stencil has to bridge. The scene is the general case.
  sources: ['spot', 'grid', 'scene', 'ramp', 'bars', 'alpha'],

  // The plugin ships no factory presets. These are the page's own, expressed
  // entirely in the plugin's parameters and reachable with the controls.
  presets: {
    'One layer, black': { layers: 0 },
    'Four layers, Street': { layers: 3, palette: C.kPalette.kStreet },
    'Paint the light (Invert)': { invert: 1 },
    'Thick bridges (1.5%)': { bridgeWidth: C.BridgeWidthParam(0.015) },
    'No speck dropping': { minIsland: 0 },
    'Nozzle close, hard edges': { distance: 0, lift: 0 },
    'Nozzle far, soft halo': { distance: C.DistanceParam(0.015) },
    'Lifted sheet, ghost bridges': { lift: 1 },
    'Heavy paint, long drips': { pressure: 0.8, drips: 1 },
    'Colours from the clip, on brick': { layers: 2, layerColours: C.kLayerColours.kFromClip, wall: C.kWall.kWallBrick },
    'Over the clip itself': { wall: C.kWall.kWallClip },
  },

  differences: [
    'The CPU half of this plugin is a PORT, not the plugin’s own code. Stencil reads the tone back to the CPU every frame and cuts each layer there (Bridge.cpp): it thresholds the tone, labels the sheet into pieces by runs and union-find, drops floating specks under Min Island, and then, pass after pass until nothing floats, gives every island the shortest bridge to any other piece, ties broken by a total order on cells, keeping last frame’s bridge while it is within a texel of the shortest. All of that is ported here to JavaScript, function for function, in cutter.js, because without it there would be no stencil. Nothing checks a port but a reader; the repository’s sntest checks the C++ and has never heard of this page.',
    'Measured once against the C++, with the same exact flood handed to both (Bridge.cpp in a scratch driver, cutter.js under node): the same bridges, the same pass counts and the same cut grid, cell for cell, on 288 frames of 48 random grids panned a little each frame (990 bridges, 794 of them kept from the frame before, 142 in a second or third pass), and on 168 frames of this page’s own cut grids (206 bridges). That is a measurement on those grids, not a guarantee for every picture.',
    'The GPU half is not a port. The detect, blur, seed, flood, second, spray, settle and composite passes are the plugin’s own GLSL — the jump flood that finds every bridge included, with the plugin’s own step schedule and its box round the floating pieces — and demo/tools/check_shaders.py fails the repository’s verify script if a character of any of them drifts. On those 168 page frames this page’s WebGL2 flood gave exactly the bridges an exact brute-force flood gives. A browser’s GPU may round the tone its own way, and a texel that sits on a threshold would then cut the other way and move a bridge.',
    'Measured once end to end: this page’s own input frames piped through the plugin’s harness (sntest --pipe, the real plugin class) gave the same picture as this page on every pixel of five frames — at the defaults, and with the cut, spray and paint controls moved — on one Apple Silicon machine, ANGLE on Metal. That is one machine and a few frames, not a guarantee for yours.',
    'The tone is read back as floats every frame, and every flood pass reads its seeds back, as the plugin’s glReadPixels calls do; WebGL2 only promises four channels for those reads, so the page reads four values a texel and keeps the first. They stall the pipeline where the plugin’s do. This is the plugin’s cost on a CPU running JavaScript: the line under the canvas says what the cutter and the floods took.',
    'The stencil is cut on the plugin’s lattice, at most 540 rows: at this page’s 960 × 540 that is a texel a pixel, as it would be at 1080p in Resolume at two pixels a texel.',
    'Last frame’s bridges are the plugin’s only state across frames. They are kept here too, in 0..1 of the lattice so a resize carries them, and forgotten when the page reloads.',
    'Layers is an FF_TYPE_INTEGER in the plugin. The kit has no integer control, so it is a dropdown of every value in the plugin’s range, 1 to 4.',
    'The plugin’s Perturb test hooks (negative controls for its harness) are not ported: none of them is part of what the plugin does in a host.',
    'There is no audio caveat and no clock caveat on this page: Stencil has no audio path and reads no time, so the drips are static and only the clip moves.',
    'The plugin’s proof — no island floats in the painted output, every bridge the brute-force shortest, bridges the stated width and 4-connected, the halo the cone’s exact chord fraction, bridges that translate with the picture — is an offline harness in the repository. Nothing on this page measures anything; the line under the canvas reports what the ported cutter did.',
  ],

  createRenderer,
});

//---------------------------------------------------------------------------
// The line under the canvas: the ported cutter's own numbers. Skipped in
// embed mode, where there is no reader.
//---------------------------------------------------------------------------
if (demo && !new URLSearchParams(window.location.search).has('embed')) {
  const stage = document.querySelector('.stage');
  if (stage) {
    const line = document.createElement('p');
    line.className = 'stage__status';
    line.dataset.cutter = '';
    stage.append(line);
    let last = '';
    const update = () => {
      if (telemetry.layers > 0) {
        const t = telemetry;
        const text = `lattice ${t.lattice} · ${t.layers} layer${t.layers === 1 ? '' : 's'} · ${t.islands} islands bridged by ${t.bridges} bridges (${t.kept} kept from the last frame) in at most ${t.passes} pass${t.passes === 1 ? '' : 'es'} · ${t.dropped} specks dropped · ${t.floating} floating · the JS cutter took ${t.cpuMillis.toFixed(1)} ms, the GPU floods and their read-backs ${t.floodMillis.toFixed(1)} ms`;
        if (text !== last) {
          line.textContent = text;
          last = text;
        }
      }
      setTimeout(update, 250);
    };
    update();
  }
}

// For driven checks: the page's handle, the telemetry and the hooks.
window.__stencilDemo = { demo, telemetry, hooks };
