"""Copy the plugin's shaders and constants into the demo, by script, never by hand.

    python3 demo/tools/sync_shaders.py          rewrite the two generated blocks
    python3 demo/tools/sync_shaders.py --print  print them instead

Two regions, each between a `//=== BEGIN GENERATED by demo/tools/sync_shaders.py (<name>)`
line and its `//=== END GENERATED (<name>)` line, belong to this script:

  - `demo/plugin.js`, (shaders): the version line and the ten GLSL bodies of
    `source/Shaders.cpp` (the vertex shader, the PCG hash the settle and the
    composite are assembled with, and detect, blur, seed, flood, second, spray,
    settle, composite), each spliced into a JavaScript template literal with its
    tabs, its comments and its blank lines exactly as they are. A template
    literal cannot hold a raw backtick, a backslash or a `${`, so those three
    would be escaped (none of the shaders has one today) and `check_shaders.py`
    undoes exactly those three and refuses any other escape;
  - `demo/controls.js`, (constants): the `constexpr` numbers of
    `source/Controls.h`, `source/Stencil.h` (the lattice and the keep slack)
    and `source/Shaders.h`, the five palettes of `source/Palette.cpp` and the
    plain wall of `source/Palette.h`, and the option names of `Controls.cpp`'s
    `PaletteName`, `LayerColoursName` and `WallName`, each literal copied as the
    C++ spells it, less a float's `f` suffix.

What this script does NOT write is the port: the functions in controls.js
(Controls.cpp, Palette.cpp's Ink, Spray.cpp), all of cutter.js (Bridge.cpp) and
the frame sequence in plugin.js (Stencil::ProcessOpenGL) are hand translations,
and only a reader -- and the one-off comparison AGENTS.md records -- checks them.

Run it whenever a shader or one of those constants changes in the plugin, then
`python3 demo/tools/check_shaders.py` (tools/verify.sh runs it) to confirm.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))

# JS constant, C++ symbol in source/Shaders.cpp, in the file's order.
SHADERS = [
    ("VERTEX_BODY", "kVertexBody"),
    ("HASH_BODY", "kHashBody"),
    ("DETECT_BODY", "kDetectBody"),
    ("BLUR_BODY", "kBlurBody"),
    ("SEED_BODY", "kSeedBody"),
    ("FLOOD_BODY", "kFloodBody"),
    ("SECOND_BODY", "kSecondBody"),
    ("SPRAY_BODY", "kSprayBody"),
    ("SETTLE_BODY", "kSettleBody"),
    ("COMPOSITE_BODY", "kCompositeBody"),
]

TARGETS = {
    "shaders": "demo/plugin.js",
    "constants": "demo/controls.js",
}


def begin(name):
    return f"//=== BEGIN GENERATED by demo/tools/sync_shaders.py ({name})"


def end(name):
    return f"//=== END GENERATED ({name})"


def read(path):
    with open(os.path.join(REPO, path)) as handle:
        return handle.read()


def cpp_shader(source, symbol):
    match = re.search(r'const char\* const ' + symbol + r' = R"\((.*?)\)";', source, re.S)
    if match is None:
        raise SystemExit(f"{symbol} not found in source/Shaders.cpp")
    return match.group(1)


def cpp_version(source):
    match = re.search(r'const char\* const kVersion = "(.*?)";', source)
    if match is None:
        raise SystemExit("kVersion not found in source/Shaders.cpp")
    return match.group(1)


def escape_template(text):
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def number(token):
    """A C++ numeric literal as JavaScript: drop a float's f suffix and an unsigned's u, nothing else."""
    token = token.strip()
    token = re.sub(r"(?<=[0-9.])f\b", "", token)
    return re.sub(r"(?<=[0-9a-fA-F])u\b", "", token)


def scalars(source, types, where):
    out = []
    for match in re.finditer(r"constexpr (?:" + types + r") (k\w+)\s*=\s*([^;{\[]+);", source):
        out.append((match.group(1), number(match.group(2))))
    if not out:
        raise SystemExit(f"no constants found in {where}")
    return out


def palettes(palette_cpp):
    match = re.search(r"const Colour kPalettes\[ controls::kPaletteCount \]\[ kCans \] = \{(.*?)\n\};", palette_cpp, re.S)
    if match is None:
        raise SystemExit("kPalettes not found in source/Palette.cpp")
    out = []
    for line in match.group(1).splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        cans = re.findall(r"\{ ([^{}]*) \}", line)
        out.append([[number(v) for v in can.split(",")] for can in cans])
    return out


def plain_wall(palette_h):
    match = re.search(r"constexpr Colour kPlainWall = \{ ([^}]*) \};", palette_h)
    if match is None:
        raise SystemExit("kPlainWall not found in source/Palette.h")
    return [number(v) for v in match.group(1).split(",")]


def names_of(source, function, count_symbol, where):
    match = re.search(
        function + r"\( int \w+ \)\s*\{\s*static const char\* const names\[ " + count_symbol + r" \] = \{ (.*?) \};",
        source,
        re.S,
    )
    if match is None:
        raise SystemExit(f"{function}'s names not found in {where}")
    return re.findall(r'"([^"]*)"', match.group(1))


def obj(pairs, indent="  "):
    return "{\n" + "".join(f"{indent}{k}: {v},\n" for k, v in pairs) + "}"


def js_rows(rows):
    return "[" + ", ".join("[" + ", ".join(r) + "]" for r in rows) + "]"


def js_strings(values):
    return "[" + ", ".join("'" + v.replace("'", "\\'") + "'" for v in values) + "]"


def shaders_block():
    shaders_cpp = read("source/Shaders.cpp")
    out = [begin("shaders") + " from source/Shaders.cpp -- do not edit by hand."]
    out.append(f"const VERSION = '{cpp_version(shaders_cpp)}';")
    out.append("")
    for name, symbol in SHADERS:
        out.append(f"const {name} = `{escape_template(cpp_shader(shaders_cpp, symbol))}`;")
        out.append("")
    out[-1] = end("shaders")
    return "\n".join(out)


def constants_block():
    controls_h = read("source/Controls.h")
    stencil_h = read("source/Stencil.h")
    shaders_h = read("source/Shaders.h")
    palette_h = read("source/Palette.h")
    palette_cpp = read("source/Palette.cpp")
    controls_cpp = read("source/Controls.cpp")

    out = [begin("constants") + " from source/ -- do not edit by hand."]
    out.append("// source/Controls.h")
    out.append("export const CONTROLS_H = " + obj(scalars(controls_h, "int|float|double", "source/Controls.h")) + ";")
    out.append("// source/Stencil.h")
    out.append("export const STENCIL_H = " + obj(scalars(stencil_h, "static constexpr int|static constexpr double|int|double", "source/Stencil.h")) + ";")
    out.append("// source/Shaders.h")
    out.append("export const SHADERS_H = " + obj(scalars(shaders_h, "unsigned|int", "source/Shaders.h")) + ";")
    out.append("// source/Palette.h")
    out.append("export const PALETTE_H = " + obj(scalars(palette_h, "int", "source/Palette.h")) + ";")
    out.append("export const PLAIN_WALL = [" + ", ".join(plain_wall(palette_h)) + "];")
    out.append("// source/Palette.cpp: five palettes of four cans, lightest first, straight RGB.")
    out.append("export const PALETTES = [")
    for rows in palettes(palette_cpp):
        out.append("  " + js_rows(rows) + ",")
    out.append("];")
    out.append("// The option lists: Controls.cpp PaletteName, LayerColoursName, WallName.")
    out.append("export const PALETTE_NAMES = " + js_strings(names_of(controls_cpp, "PaletteName", "kPaletteCount", "source/Controls.cpp")) + ";")
    out.append("export const LAYER_COLOURS_NAMES = " + js_strings(names_of(controls_cpp, "LayerColoursName", "kLayerColoursCount", "source/Controls.cpp")) + ";")
    out.append("export const WALL_NAMES = " + js_strings(names_of(controls_cpp, "WallName", "kWallCount", "source/Controls.cpp")) + ";")
    out.append(end("constants"))
    return "\n".join(out)


BLOCKS = {"shaders": shaders_block, "constants": constants_block}


def region(text, name):
    start = text.find(begin(name))
    stop = text.find(end(name))
    if start < 0 or stop < 0 or stop < start:
        return None
    return start, stop + len(end(name))


def main():
    if "--print" in sys.argv:
        for name in BLOCKS:
            print(BLOCKS[name]())
            print()
        return 0
    for name, path in TARGETS.items():
        full = os.path.join(REPO, path)
        with open(full) as handle:
            text = handle.read()
        where = region(text, name)
        if where is None:
            raise SystemExit(f"{path} has no ({name}) generated block")
        updated = text[: where[0]] + BLOCKS[name]() + text[where[1]:]
        if updated == text:
            print(f"{path}: the ({name}) block already matches source/")
            continue
        with open(full, "w") as handle:
            handle.write(updated)
        print(f"{path}: the ({name}) block rewritten from source/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
